apiVersion: v1
data:
  CLOUDINARY_API_KEY: NzgzMTY5MzcxODMxMjQ3
  CLOUDINARY_API_SECRET: anhRaEtTUlFvZl81TXkxSXhrUk40YUFXMzRR
  CLOUDINARY_CLOUD_NAME: ZHJ5bXJtOXJz
  JWT_PUBLIC_KEY: TFMwdExTMUNSVWRKVGlCUVZVSk1TVU1nUzBWWkxTMHRMUzBLVFVsSlFrbHFRVTVDWjJ0eGFHdHBSemwzTUVKQlVVVkdRVUZQUTBGUk9FRk5TVWxDUTJkTFEwRlJSVUZxZDNCdGRFOHhVbWt2VldweGRWUlNjRlYwU3dwVVZFSk5lR0ZpU2tkVlZXczViSHBaVjJSQ1lTOVpjMnROU1RsQ2JGY3dZbk00VlhKWU9DOHlWMjVGVURONVRpOUpXVWxLY1hOM1J6UkVXa1kxVkhwRkNqZ3lOM2RIZWpkd1dFSXpWV3gxZG1OWVJrcDZjRE4zYUc5c1ZESlpSMUUwTUhJMVJuUkxSMnBtTUZOYWJGZFdNVkZpVkVwbUwydGxPVzVoVDJ0SVdsY0tVRlZUTjNoTWMyVTJRbGRvV1VveVIyRXJPWEpFZWxGakwzUm1hRGRJTDJGUVdWbE5XRFI1VEUxeGNUZGtjV2x0TkVWR1YzSkNVVk5KVUU1aWVXcEpad3BRUXk4MU5qUkhTbTQyVHpOUk1rVTBPRTR4TDBSMVpFMVdhRVZQTTJWdmEzUTNXVWRITmtSQlIyUkJVMWRKVDBFMmFUQkpkR05zWkdrd2JtOTJXRkp0Q2taQmEyWm1Oa1J1YVZvM1ZWbHlabEZqZUNzMVFsTkhXVWREWjJsYVNYUXpSVmhPTVVGTU1rMVRjVGgwZFZVeVpIaGxSa1kzZWtFMWFFUjZaVTlYU1c0S01uZEpSRUZSUVVJS0xTMHRMUzFGVGtRZ1VGVkNURWxESUV0RldTMHRMUzB0Q2c9PQ==
  JWT_SECRET: bXlMaXR0bGVTZWNyZXQ=
  KAFKA_BROKER: a2Fma2E6OTA5Mg==
  MONGODB_URI: bW9uZ29kYitzcnY6Ly91c2VNb25nbzp1c2VNb25nb0BjbHVzdGVyMC5ybHVzY2J5Lm1vbmdvZGIubmV0L0V2ZW50LUJvb2tpbmctT3JnYW5pemUtU2VydmljZT9yZXRyeVdyaXRlcz10cnVlJnc9bWFqb3JpdHkmYXBwTmFtZT1TaHViaGFt
  NODE_ENV: ZGV2ZWxvcG1lbnQ=
  PORT: NTAwMw==
kind: Secret
metadata:
  creationTimestamp: null
  name: organize-service-secrets
