apiVersion: v1
data:
  KAFKA_BROKER: a2Fma2E6OTA5Mg==
  MONGODB_URI: bW9uZ29kYitzcnY6Ly91c2VNb25nbzp1c2VNb25nb0BjbHVzdGVyMC5ybHVzY2J5Lm1vbmdvZGIubmV0L0V2ZW50LUJvb2tpbmctRGlzY292ZXJ5LVNlcnZpY2U/cmV0cnlXcml0ZXM9dHJ1ZSZ3PW1ham9yaXR5JmFwcE5hbWU9U2h1YmhhbQ==
  NODE_ENV: ZGV2ZWxvcG1lbnQ=
  PORT: NTAwNA==
kind: Secret
metadata:
  creationTimestamp: null
  name: event-discovery-secrets
